import * as express from "express";
import authenticateToken from "../../middleware/authMiddleware.js";
import { createUser, getUsers, getUser, updateUser, editPassword } from "../controllers/user.controller.js";
import upload from "../../middleware/uploadMiddleware.js";
const router = express.Router();
router.post("/", upload.single('image'), createUser);
router.get("/", authenticateToken, getUsers);
router.get("/:id", authenticateToken, getUser);
router.put("/:id", [authenticateToken, upload.single('image')], updateUser);
router.put("/change-password/:id", authenticateToken, editPassword);
export default router;
